<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>Ultrarogue</AssemblyName>
    <Product>ULTRAROGUE</Product>
    <GUID>com.bananastudio.ultrarogue</GUID>
    <Version>0.2.3</Version>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <RootNamespace>Ultrarogue</RootNamespace>
    <UltrakillDir>YOUR_PATH_TO_ULTRAKILL</UltrakillDir> <!-- Ensure that this has BepInEx installed -->
    <UltrakillManagedDir>$(UltrakillDir)ULTRAKILL_Data/Managed/</UltrakillManagedDir>
    <CopyToBepInExPluginsDir>false</CopyToBepInExPluginsDir>

    <RestoreAdditionalProjectSources>
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <Import Project="Properties/DeployToPlugins.targets" />

  <ItemGroup>
    <None Remove="catalog.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="catalogStuff\**\*.*" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ItemIcons\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Assembly-CSharp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="Krafs.Publicizer" Version="2.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="UltraModding.PluginInfoGenerator" Version="4.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.28" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(UltrakillManagedDir)Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>$(UltrakillManagedDir)Facepunch.Steamworks.Win64.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(UltrakillManagedDir)Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="plog">
      <HintPath>$(UltrakillManagedDir)plog.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(UltrakillManagedDir)Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Unity.AI.Navigation">
      <HintPath>$(UltrakillManagedDir)Unity.AI.Navigation.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(UltrakillManagedDir)Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>$(UltrakillManagedDir)Unity.ResourceManager.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(UltrakillManagedDir)Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.TextCoreFontEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.TextCoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.TextCoreTextEngineModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(UltrakillManagedDir)UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(UltrakillManagedDir)UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
